import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
import Footer from "../Mycomponents/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {Navbar()}
        {children}
        <Footer />
      </body>
    </html>
  );
}

const Navbar = () => {
  return (
    <div className="w-full h-24 flex justify-end items-center px-4">
      <div className="w-full flex justify-end items-center ">
        <Link
          href="/About"
          className="mx-2 text-base sm:text-2xl font-semibold poppins-light hover:text-amber-400 hover:border-b-2 border-amber-400"
        >
          About
        </Link>

        <Link
          href="/Career"
          className="mx-2 text-base sm:text-2xl font-semibold poppins-light hover:text-amber-400 hover:border-b-2 border-amber-400"
        >
          Chat With Us
        </Link>
        <Link
          href="/Services"
          className="mx-2 text-base sm:text-2xl font-semibold poppins-light hover:text-amber-400 hover:border-b-2 border-amber-400"
        >
          Services
        </Link>

        <div className="ml-4">
          <Link href="/">
            <Image
              src="/envelope.png"
              alt="LOGO"
              width={70}
              height={70}
              className="w-10 sm:w-16 md:w-15 h-auto object-cover object-center"
            />
          </Link>
        </div>
      </div>
    </div>
  );
};
