import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {Navbar()}
        {children}
      </body>
    </html>
  );
}

const Navbar = () => {
  return (
    <div className="w-full h-24 flex justify-end items-center  ">
      <div className="w-full h-10  flex justify-end items-center">
        <Link
          href="/About"
          className="m-3 sm:text-2xl font-bold text-sm poppins-light hover:text-amber-400 hover:border-b-2 border-amber-400"
        >
          About
        </Link>
        <Link
          href="/About"
          className="m-3 sm:text-2xl w-28 sm:w-auto  font-bold text-md poppins-light hover:text-amber-400 hover:border-b-2 border-amber-400"
        >
          Contact Us
        </Link>

        <Link
          href="/About"
          className="m-3 sm:text-2xl font-bold text-md poppins-light hover:text-amber-400 hover:border-b-2 border-amber-400"
        >
          Career
        </Link>
        <div className="w-40 h-10  ml-10 relative">
          <Link href="/">
            {" "}
            <Image
              src="/envelope.png"
              alt="LOGO"
              width={70}
              height={70}
              className="object-cover object-center"
            />
          </Link>
        </div>
      </div>
    </div>
  );
};
